name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - unify-tests

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        thing:
        - x86_64-mingw
        - i686-msvc
        - x86_64-msvc
        include:
        - thing: x86_64-mingw
          target: x86_64-pc-windows-gnu
          rust: stable
          os: windows-latest
          test-type: run
        # CI's Windows doesn't have required root certs,
        # breaking tokio-boring and hyper-boring tests.
        - thing: i686-msvc
          target: i686-pc-windows-msvc
          rust: stable-x86_64-msvc
          os: windows-latest
          test-type: run-without-hyper
        - thing: x86_64-msvc
          target: x86_64-pc-windows-msvc
          rust: stable-x86_64-msvc
          os: windows-latest
          test-type: run-without-hyper

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install Rust (rustup)
      run: rustup update ${{ matrix.rust }} --no-self-update && rustup default ${{ matrix.rust }}
      shell: bash
    - run: rustup target add ${{ matrix.target }}
    - name: Install nasm
      if: startsWith(matrix.os, 'windows')
      run: choco install nasm
      shell: cmd
    - name: Install LLVM and Clang
      if: startsWith(matrix.os, 'windows')
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "11.0"
        directory: ${{ runner.temp }}/llvm
    - name: Install musl support
      if: contains(matrix.target, 'musl') && startsWith(matrix.os, 'ubuntu')
      run: sudo apt update && sudo apt install musl-tools
    - name: Set LIBCLANG_PATH
      if: startsWith(matrix.os, 'windows')
      run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
    - if: matrix.test-type == 'run-without-hyper'
      run: cargo test --target ${{ matrix.target }} --workspace --exclude tokio-boring --exclude hyper-boring
      name: Run tests (without hyper)
    - if: matrix.test-type == 'run'
      run: cargo test --target ${{ matrix.target }}
      name: Run tests
    - if: matrix.test-type == 'build-only'
      run: cargo test --target ${{ matrix.target }} --no-run
      name: Build tests
